### PR TITLE
Button

### PR DESCRIPTION
**Pull request by samflab**
hey this is a button component. please review it.

### CODE REVIEW

**Review by znjs — APPROVED** [review]
👍

**Review by rutvikpumak — APPROVED** [review]

**Review by Nishant-96 — APPROVED** [review]
Approved

**Review by mohammadkhizerkhan — APPROVED** [review]
add box-sizing property

**Review by muskaanshah — APPROVED** [review]

**Review by pavan6115 — CHANGES_REQUESTED** [review]
Nice component

**Review by ScoobyDubeyDo — APPROVED** [review]

**Review by SubhamChoudhury — APPROVED** [review]
looks great

**Review by SK02K1 — APPROVED** [review]
masudha op

**Pull request closed without merging**
